### ISSUE TITLE
Including other Bootstrap plugins - like Scrollspy

### ISSUE THREAD

**Issue by erikberger** [tatygrassini/landio-html#11]
This is more of a question than an issue so I apologize if this isn't the appropriate forum.

I'd like to enable Scrollspy. I know that I can include the code manually, but I am trying to learn the "right way" using modern tools. The file /js/landio.js has a bunch of @codekit-prepend comments that reference the different bootstrap plugins. If I add:

`// @codekit-prepend "bootstrap/scrollspy.js";`

it appears I would need to purchase codekit to compile this correctly?

Or are there commands I can enter into Terminal like SASS?

**Comment by tatygrassini** [comment]
Scrollspy is not supported in Landio. Yes, Codekit was used to build the template, but, buying the app is up to you, I guess. There are free options like Codekit you could use, adapting the code, of course. Or implementing any task runner (Grunt / Gulp). Best of lucks!
