### ISSUE TITLE
Updating bootstrap

### ISSUE THREAD

**Issue by z1haze** [tatygrassini/landio-html#12]
This is just a question, but do you think you'd consider updating this to the beta, or maybe wait until 4 is actually released and completely update it to 4? This is a really nice starter template/uikit that I've used multiple times already, I just wonder if it will make it to the newest versions.

**Comment by tatygrassini** [comment]
It's in the works with lots of changes and improvements in the file structure.

**Comment by z1haze** [comment]
I think the appropriate thing to do would be keep this issue open and then reference the commit that fixes this.

**Comment by antonellopasella** [comment]
is there any branch with a preview? thanks for the great work!

**Comment by tatygrassini** [comment]
@z1haze @antonellopasella Landio is updated !! 👍
