### ISSUE TITLE
Suggestion: Separate landio and bootstrap css

### ISSUE THREAD

**Issue by oleteacher** [tatygrassini/landio-html#15]
Wonderful template and we use it in many classroom projects. Thank you!

Maybe this is not possible or you have other reasons but... Separate the css so easier to update bootstrap to current releases.

Thanks for at least considering:)

Susan

**Comment by tatygrassini** [comment]
Hi Susan, BS is updated to the latest version now (v4.1.3).

The reason to avoid multiple CSS and JS HTTP requests is obviously performance. More detailed info in the Codrops [post](https://tympanus.net/codrops/2015/10/17/freebie-land-io-ui-kit-landing-page-template-html/) I wrote some time ago.

**Comment by oleteacher** [comment]
Thanks Taty. Hard to argue with you as the template has the speed:)
