### ISSUE TITLE
navbar-fixed-top not working?

### ISSUE THREAD

**Issue by compito** [tatygrassini/landio-html#2]
Hi, I've just tried this out, and navbar-fixed-top doesn't seem to work as expected. I tried switching to navbar-fixed-bottom and it works as it should. Any idea why it is behaving  like that? Or did I missed something?

Thanx for a lovely template

**Comment by tatygrassini** [comment]
This is a landing page design with nav links pointing to external pages, dropdowns...

Fixed navigation would make sense in a one-page website context (it is not), links pointing to a section and all... So no, no support for that.

Used `.navbar-fixed-top` to place the nav on top of the full screen hero `.jumbotron` section. The override to avoid fixed position is here:

https://github.com/tatygrassini/landio-html/blob/master/scss/landio.scss#L284

Removing that line gives you back the original BS fixed nav, styling links contrast on scroll is up to you.
