### ISSUE TITLE
Domain name

### ISSUE THREAD

**Issue by ghost** [tatygrassini/landio-html#3]
Why this named like registered domain name? Confusing.

**Comment by tatygrassini** [comment]
How is that a relevant issue? It was named after the original design (Land.io).

**Comment by ghost** [comment]
I had checked land.io to see if it is relevant. I think i am not alone. What is the base land.io repo? Link would be nice.

**Comment by tatygrassini** [comment]
This is a free template with a fake name. Land.io doesn't mean anything, there's no URL registered for it. 

You're free to download it, edit it, change its title, name, logo... make it your own.

Not sure if there's another Land.io repo out there, this one was created exclusively for Codrops (the original design was published there).

And yes, I'm afraid you're alone in this one, no one else is asking the same anywhere.

**Comment by Firestorm-Graphics** [comment]
not sure what issue is either, would you rather receive a free template with no content so you have to guess whats what and guess how it would look ?? do themeforest demo templates have no content ?? im sure they do. so its clear, its a template name and used as a DEMO website name
