### ISSUE TITLE
Play button on videos

### ISSUE THREAD

**Issue by 2braincells2go** [tatygrassini/landio-html#5]
Nice theme!

Cannot seem to get any type of play button to appear on the videos. Have tried the stand alone mp4 and YouTube versions. Currently you must find exact spot to get video to play and many visitors would never find. Tried on Chrome, IE 10 and Edge.

Also would be very helpful to have unminified version of CSS to make tweaks much simpler.

Thanks for sharing this excellent theme.

**Comment by tatygrassini** [comment]
Thank you!

Did a quick test on the same browsers you mentioned, it all seems to be OK.

Please check if you have the icon font files in the `css/fonts/` folder, that's the only reason I guess play button isn't there. Initial play action is on the button itself, after that, clicking anywhere gives you play/pause in all 3 versions.

For performance reasons, CSS is minified, and can be easily uncompressed and edited using any preprocessor tools, like Codekit (config file included in the download), Koala (free), Grunt, Gulp... you get the point.

If you still have that issue, please share some URL and I'll be happy to help.
