### ISSUE TITLE
ios issue

### ISSUE THREAD

**Issue by Firestorm-Graphics** [tatygrassini/landio-html#6]
when loading the demo in ios 9.1 & 9.2 beta in safari and chrome the animation causes the viewport to decrease in size momentarily until the animation has completed

**Comment by tatygrassini** [comment]
Checked on iOS9.1/iPhone 6, all seems OK there. Any additional info could help to replicate the problem. Exactly what demo page (URL), what animation is causing the issue (section), any chance to upload a Gif?

**Comment by Firestorm-Graphics** [comment]
its the url from the readme here on github, scroll down to the tables and as the first table loads the width narrows untill that animation has finished

**Comment by tatygrassini** [comment]
Thank you, I just needed a reason to disable animations on mobile. All seems to be working fine now. Plus, I improved the navigation links spacing for better "tapping" on small screens.

**Comment by Firestorm-Graphics** [comment]
thanks for that, i seem to have discovered that just by adding shrink-to-fit=no seems to work as a fix as below:

``` html
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, shrink-to-fit=no">    
```
