### ISSUE TITLE
App Store and Instagram icons

### ISSUE THREAD

**Issue by taktikal17** [tatygrassini/landio-html#8]
Hi @tatygrassini, 

Thank you for this template! I love it! :+1: :+1: :+1: 
I am wondering whether you had already integrated an App Store and an Instagram icon which match with the landio design?

I would like to use the Apple app store logo in your button and the instagram icon with the other social media ( Facebook and twitter)

Thanks a lot!

Have a good one! :100:

**Comment by tatygrassini** [comment]
![image](https://cloud.githubusercontent.com/assets/185308/14409977/bc7e9a3a-ff22-11e5-91c7-6db1e7750694.png)

You got it!

**Comment by taktikal17** [comment]
Thank you a lot @tatygrassini !! :100: 

Have a good one!
